### ISSUE TITLE
Example no running in shiny-server

### ISSUE THREAD

**Issue by gonzalezivan90** [jcrodriguez1989/shinyParallel#4]
Hi all! The example provided in the documentation is not running for me. I use to have regular shinny apps and now under the shinyParallel configuration is not working. 
I'm doing something wrong?

Step0. Install shiniParallel
Step1. Create the app.R file into /srv/shiny-server/myShinnyApp folder. No shiny::runApp() or shinyParallel::runApp() command at the end. Here a single directory and single app.R file are created
Step2. Run the shinyParallel::installShinyParallel( ) function in a R console having '/srv/shiny-server' as a working directory. Here a shortcut to "/srv/shiny-server/shinyParallel_appLinks/myShinyApp" folder is created with N subfolder replicates of the app, provided as an argument in the function called in this step. Each subfolder myShinyApp_[N] has a app,  global, server, settings and ui R files. 
Step 3. Launch the [IP]:[port]/myShinyApp/ page. All blank, not working.
Step 4. Launch the [IP]:[port]/myShinyApp/?admin. A render table with users. Is working.

My original port is 3838. All shiny apps are running, but no with shinyParallel configuration. Some advice?
Thanks!

**Comment by jcrodriguez1989** [comment]
Hi, I had the chance to test out your issue.
Please try to follow this.
1. First, delete all wrongly (**check out you don't delete important files**) created files at `/srv/shiny-server/` .
2. Then, for `Step1` the `app.R` file should not be created into `/srv/shiny-server/` subfolders. You should create it anywhere else, for example at `/tmp/myShinyApp/app.R`.
3. Enter R, and type `shinyParallel::installShinyParallel("/tmp/myShinyApp/")`
4. Try to enter from a browser to http://localhost:3838/myShinyApp/

Please, let me know if it still does not work.

**Comment by gonzalezivan90** [comment]
Works good! My mistake was running the file from ´/srv/shiny-server/*´
Thanks, Juan

**Comment by jcrodriguez1989** [comment]
I am glad it worked :)
